name: Build and Push Docker Image to Docker Hub

on:
  push:
    branches:
      - develop  # main 브랜치에 푸시될 때 실행

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      # 빌드하기 위해 github Action에 jdk를 설치
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
            distribution: 'temurin'
            java-version: '17'

        # Gradle 빌드 (bootJar 실행)
      - name: Build JAR with Gradle
        run: |
          chmod +x gradlew
          ./gradlew clean build -x test

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and Push Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/tourism-app:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/tourism-app:latest
